import sys

print('Enter the file name complete with the file path (e.g. D:/Current/Data science/Python/My glossary_En-Ru.txt)')
original_filename = input()
original_file = open(original_filename, 'r')


print('Enter dictionary name. This name will be used by Lingvo. This is not file name')
dict_name = input()
print("Enter source language from Lingvo's language list. E.g. English, Russian")
source_lang = input()
print("Enter target language from Lingvo's language list. E.g. English, Russian")
tgt_lang = input()

#Lingvo tag definition depending on the dictionary type (bilinqual or monolingual)
if source_lang == tgt_lang:
    colnum = 5
    opening_tag = [None, '    [trn][i]', '    [trn]', '    [ex][c darkgray]', '    [com][c]']
    closing_tag = [None, '[/i][/trn]\n', '[/trn]\n', '[/c][/ex]\n', '[/c][/com]\n']
else:
    colnum = 6
    opening_tag = [None, '    [trn][i]', '    [trn]', '    [trn][i]', '    [ex][c darkgray]', '    [com][c]']
    closing_tag = [None, '[/i][/trn]\n', '[/trn]\n', '[/i][/trn]\n', '[/c][/ex]\n', '[/c][/com]\n'] 

converted_filename = original_filename[:-3] + 'dsl'
converted_file = open(converted_filename, 'w')
converted_file.write('#NAME "' + dict_name + " " + source_lang[:2] + '-' + tgt_lang[:2] + '"' + '\n')
converted_file.write('#INDEX_LANGUAGE "' + source_lang + '"' + '\n')
converted_file.write('#CONTENTS_LANGUAGE "' + tgt_lang + '"' + '\n')

entry=[line for line in original_file]
diclen = len(entry)
k = 1
entry_num = -1

for i in entry:
    entry_num = entry_num + 1
    i = i.rstrip('\n')
    if i == '\t' * (colnum - 1):
        original_file.close()
        converted_file.close()
        sys.exit('Error: empty entry. Sort the sheet alphabetically in Excel before saving')
#Checking for paragraph breaks within entry parts. There should be none, so there should always be 5 tabs).
    if i.count('\t') < colnum - 1:
        original_file.close()
        converted_file.close()
        error_mes = 'Error. Forbidden paragraph break in the following entry: ' + i
        sys.exit(error_mes)
    if i.count('\t') > colnum - 1:
        original_file.close()
        converted_file.close()
        sys.exit('Error: too many columns.')
    i = i.replace('""', '"')  #Replacing double double quotes (generated by a bug in Excel to TXT conversion)
    #Removing spaces at the begining of headword. Otherwise Lingvo will not consider it a headword
    i = i.lstrip()
    i = i.split('\t')
    #Removing spaces at the end of headword as Python considers headword with space at the end different 
    #from same headword without spaces and Lingvo considers them to be identical  resulting in conversion error
    i[0] = i[0].rstrip()
    print(i[0])
    #Comparing headword with previous entries
    if entry_num > 0:
        prev_entry = entry[entry_num-k]
        prev_entry = prev_entry.split('\t')
        prev_headword = prev_entry[0].strip()
        if i[0] == prev_headword:
            k = k + 1
        else:
            converted_file.write(i[0] + '\n')
            k = 1
    else:
        converted_file.write(i[0] + '\n')
    for j in range(1, colnum):
        i[j] = str(opening_tag[j]) + str(i[j]) + str(closing_tag[j])
        if i[j] == str(opening_tag[j]) + str(closing_tag[j]):
            i[j] = ''
        converted_file.write(i[j])
       

original_file.close()
converted_file.close()
